// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = (function() {
    var obj;
    return obj = {
      test1: function() {
        return console.log('Test 1 was called');
      },
      test2: function() {
        return console.log('Test 2 was called');
      }
    };
  })();

}).call(this);
