// Generated by CoffeeScript 1.9.3
(function() {
  exports.test = function() {
    return console.log('Test Helper function called');
  };

  exports.test2 = function() {
    return console.log('Test 2 was called');
  };

  exports.hashPassword = function(plainPassword, salt, cb) {
    if (cb == null) {
      cb = function() {};
    }
    return bcrypt.hash(plainPassword, salt, function(err, hash) {
      if (err) {
        return cb(err, null);
      }
      return cb(null, hash);
    });
  };

}).call(this);
