// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(passport, LocalStrategy) {
    passport.use('local-db', new LocalStrategy({
      usernameField: 'email',
      passwordField: 'password'
    }, function(email, password, done) {
      return GLOBAL.db.User.findByEmail(email, function(user) {
        if (!user) {
          return done(null, false, {
            message: 'Incorrect email.'
          });
        }
        return user.isValidPassword(password, function(err, status) {
          if (status === false) {
            return done(null, false, {
              message: 'Incorrect password.'
            });
          }
          if (status === true) {
            return done(null, user);
          }
        });
      });
    }));
    passport.serializeUser(function(user, done) {
      return done(null, user.id);
    });
    passport.deserializeUser(function(id, done) {
      return GLOBAL.db.User.findById(id, done);
    });
  };

}).call(this);
