// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(express, app) {
    var router;
    router = express.Router();
    router.get('/login', function(req, res, next) {
      console.log(req.flash('error'));
      console.log(req.flash('info'));
      console.log(req.flash('warning'));
      return res.render('auth/login', {});
    });
    router.post('/login', passport.authenticate('local-db', {
      successRedirect: '/',
      failureRedirect: '/login',
      failureFlash: true
    }));
    router.get('/logout', function(req, res, next) {
      req.logout();
      return res.redirect('/');
    });
    return app.use('/', router);
  };

}).call(this);
