// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(express, app) {
    var router;
    router = express.Router();
    router.get('/', function(req, res, next) {
      return res.render('index');
    });
    router.get('/about', function(req, res, next) {
      return res.send('<h1> About Express</h1>');
    });
    return app.use('/', router);
  };

}).call(this);
