// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(express, app) {
    var router;
    router = express.Router();
    router.get('/user', function(req, res, next) {
      res.locals = {
        'message': 'LiteBreeze',
        'data': [
          {
            'name': 'Praveesh',
            'id': 2
          }, {
            'name': 'Praveen',
            'id': 10
          }, {
            'name': 'Akhil',
            'id': 15
          }
        ]
      };
      return res.render('user-list', {});
    });
    return app.use('/', router);
  };

}).call(this);
