// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(env) {
    var config;
    config = require(__dirname + '/../config/config.json');
    return config[env];
  };

}).call(this);
